server:
  port: 9555
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka/
spring:
  application:
    name: gamesdk-zuul
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#zuul:
#  routes:
#    login:
#      path: /gamesdk/login/**
#      service-id: LOGIN
#    pay:
#      path: /gamesdk/pay/**
#      service-id: PAY
zuul:
  routes:
    #gamesdk-login: /gamesdk-login/**
    #gamesdk-pay: /gamesdk-pay/**
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh