server:
  port: 9555
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
#zuul:
#  routes:
#    login:
#      path: /gamesdk/login/**
#      service-id: LOGIN
#    pay:
#      path: /gamesdk/pay/**
#      service-id: PAY 
zuul:
  routes:
    gamesdk-login: /gamesdk-login/**
    gamesdk-pay: /gamesdk-pay/**
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh